  version: '3'
  
  services:
  
    todoback:
      build: ./todo-app/back-end
      restart: always
      ports:
        - 3001:3001

    todofront:
      depends_on:
        - todoback
      build: ./todo-app/front-end
      restart: always
      environment:
        - REACT_APP_API_HOST=todoback
        - REACT_APP_API_PORT=3001
      ports: 
        - 3000:3000

    todotests:
      build: ./todo-app/tests
      depends_on:
        - todoback
        - todofront
      restart: always
      environment:
        - FRONT_HOST=todofront